### ISSUE TITLE
What does & do after function name?

### ISSUE THREAD

**Issue by aminroosta** [ddinu/observable#1]
Hi @ddinu 
```c++
auto unsubscribe() &
{
        if(!called_->test_and_set())
        {
            try {
                unsubscribe_();
            } catch(...) {
                called_.reset();
                throw;
            }
        }
}
```

What does `&` do in `auto unsubscribe() & { ...` ?
Or `&&` in `auto release() && { ...`

Thanks in advance.

**Comment by offa** [comment]
This allows to overload methods based on whether it's called on an r-value (`&&`) or l-value (`&`). It also limits the usage to these kind; `unsubscribe()` is only callable on a l-value, while `release()` is only callable on a r-value.

**Comment by aminroosta** [comment]
@offa Thank you very much :-) 

``` c++
#include<iostream>
using namespace std;

struct Test {
  auto print() & { cout << "lvalue" << endl; }
  auto print() && { cout << "rvalue" << endl; }
};

int main() {
  Test t;
  t.print(); // lvalue
  Test().print(); // rvalue
}
```
