### ISSUE TITLE
Documentation is incomplete?

### ISSUE THREAD

**Issue by mlimber** [ddinu/observable#2]
Seems like the documentation is mostly empty files? Am I missing it?

What advantage is there in this library over, say, Boost.Signal2?

**Comment by ddinu** [comment]
Hi @mlimber,

Indeed, part of the documentation is incomplete. I'm planning on adding more documentation as soon as I get some free time.

The difference from Boost.Signal2 is mainly in having dedicated properties that can be used as class members (which cannot be changed from outside your class). You can do something similar with Boost and even Qt, but you need to write a few lines of code yourself.

This is an alternative for when you need observable properties and not signals and slots. People can use whatever is best for their case.

**Comment by ddinu** [comment]
All major functionality has been documented.
