### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [ddinu/observable#22]
Would you like to [replace any double quotes](https://github.com/ddinu/observable/blob/a1c9d93bbf775b1ef5ec44158ebbb58e638379f2/include/observable/observable.hpp#L4 "Update candidate") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by ddinu** [comment]
Sure, I think I went with quotes just out of habit. Angle brackets make sense for a library.

**Comment by elfring** [comment]
Thanks for [your source code adjustments](https://github.com/ddinu/observable/commit/56c34bebc5f70e2739f02a9e6883e263cef5ba03 "Switch include style to angle brackets.").

**Comment by ddinu** [comment]
No problem. Thanks for pointing out the problem!
