### ISSUE TITLE
Should be able to subscribe to a const observable value.

### ISSUE THREAD

**Issue by bkuhns** [ddinu/observable#23]
I'm trying out this pretty awesome library and ran into a bit of a hiccup. I want some code to take a `const&` to my view-model (which contains `obvservable::value<>` members) and that code needs to add some subscriptions for changes to the view-model's state. I understand that adding a subscription to a `value` modifies its state internally (to maintain a list of subscribers), but I feel that subscribing is "logically const". By subscribing, I don't want to affect the state of a `value`, I simply want to be informed when the state changes. So, it seems correct to allow new subscriptions on `const value<>` types.

**Comment by ddinu** [comment]
Thanks for the bug report.

Fixed by commit  993b0c99.
