### ISSUE TITLE
Is BehaviourSubject possible?

### ISSUE THREAD

**Issue by sdelaysam** [ddinu/observable#26]
Hello, 
It would be cool to keep state of subject even if there are no subscribers at a moment, just like BehaviourSubject do.
Please share your thoughts about it.
Thanks, in general your library is what I was looking for 👍

**Comment by ddinu** [comment]
Hi @sdelaysam,

Subjects themselves are "stateless" but values could do something similar to BehaviousSubject. I think that supporting something like that would be useful.

I'm thinking of adding a new method on values: `value::subscribe_notify(...)` or maybe `value::subscribe_initialize(...)` or `value::subscribe_call(...)`. I'm not sure what the best name would be.

Would something like that be close to what you had in mind?

-Daniel

**Comment by sdelaysam** [comment]
Cool, `value` could fit the needs of using `BehaviourSubject`!
Maybe `value::subscribe_get(...)` ?

**Comment by ddinu** [comment]
Added `subject::subscribe_and_call(...)` and `value::subscribe_and_call(...)`.
