### ISSUE TITLE
Weird debugger behaviour

### ISSUE THREAD

**Issue by sdelaysam** [ddinu/observable#28]
Hello @ddinu 

This looks like a Clang/LLDB problem, but would be great to hear any ideas. I will attach the small project of several lines of code.

**Problem:**  LLDB suddenly crashes when debugging code with `observable::value<Foo>` if `Foo` is within a namespace. Works fine if `Foo` is global. `observable::subject<Foo>` works perfectly in both cases. Everything works fine when using GCC.

**Environment:**  
MacOS Sierra 10.12.6 (16G29)
Xcode 9.0 (9A235)
Clang Apple LLVM version 9.0.0 (clang-900.0.37)
LLDB version lldb-900.0.45 Swift-4.0

Tested in Xcode and CLion. 

[test.zip](https://github.com/ddinu/observable/files/1391713/test.zip)

**Comment by ddinu** [comment]
Sorry for the late reply.

That is indeed weird, but I'm afraid that I can't help too much with this; I don't have access to a Mac that I could use to debug the problem.

I did try your example code with Visual Studio 2017 and it works without any problems.

**Comment by ddinu** [comment]
I'm closing this issue, but please reopen if it's still a problem.
