### ISSUE TITLE
Add a way to unsubscribe

### ISSUE THREAD

**Issue by fran6co** [ddinu/observable#30]
Should be possible to unsubscribe in the case an observer is no longer valid.

**Comment by fran6co** [comment]
Ah, nevermind I just found how

**Comment by StaticLink** [comment]
@fran6co @ddinu Hi guys, do you recall how this is done? I just adopted ddinu.observable, and I can't find it mentioned in the reference. (very good library otherwise 😃)

**Comment by StaticLink** [comment]
> @fran6co @ddinu Hi guys, do you recall how this is done? I just adopted ddinu.observable, and I can't find it mentioned in the reference. (very good library otherwise 😃)

Nevermind :) - In the reference, it's mentioned that subject.subscribe

**Returns** _An unique subscription that can be used to unsubscribe the provided observer from receiving notifications from this subject._

**Comment by ddinu** [comment]
Hi @StaticLink 

I'm happy to hear you found the answer. Please feel free to post any issues you run into.

Regards,
Daniel
