### ISSUE TITLE
Add support for C++17

### ISSUE THREAD

**Issue by mohitisgreat** [ddinu/observable#32]
`std::result_of` and `std::result_of_t` has been deprecated by C++17. When using the library with C++17 enabled we face several errors in the file `utility.hpp` .

> 1>observable\expressions\utility.hpp(79): error C4996: 'std::result_of_t': warning STL4014: std::result_of and std::result_of_t are deprecated in C++17. They are superseded by std::invoke_result and std::invoke_result_t. You can define _SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
> 1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\type_traits(1855): note: see declaration of 'std::result_of_t'

**Comment by ddinu** [comment]
Hi @mohitisgreat,

Thanks for reporting this. I'll fix it in the next few days.

**Comment by ddinu** [comment]
The issue was fixed in commit c7d0850dfda1c1cd88476dca639d48b6ea239733.

This shouldn't be needed, but if you still get warnings with Visual Studio, please pass the `/Zc:__cplusplus` flag.
