### ISSUE TITLE
Methods of subscription cannot be called in parallel as documentation claims

### ISSUE THREAD

**Issue by markazmierczak** [ddinu/observable#33]
The `shared_subscription::unsubscribe` method cannot be called in parallel from multiple threads as documentation claims.

> A shared_ptr instance can be "read" (accessed using only const operations) simultaneously by multiple threads. Different shared_ptr instances can be "written to" (accessed using mutable operations such as operator= or reset) simultaneously by multiple threads (even when these instances are copies, and share the same reference count underneath.)
>
> Any other simultaneous accesses result in undefined behavior.

**Comment by ddinu** [comment]
Good catch. I'll try to get a fix ready in the next few days. Thanks for the bug report!

**Comment by ddinu** [comment]
Fixed. Please let me know if there's any problem with the fix.
