### ISSUE TITLE
cmake 3.8 version not necessary

### ISSUE THREAD

**Issue by CapSel** [ddinu/observable#34]
Is it necessary to have 3.8 version of cmake required?
Android Studio provides 3.6.

**Comment by ddinu** [comment]
That's a good question. I don't think it's required, but I'll need to run some tests to make sure.

**Comment by ddinu** [comment]
[Fixed](https://github.com/ddinu/observable/commit/b2aa4c640ee1fe06a97ca54fccc81add9f3a0035)
