### ISSUE TITLE
Observable properties and threading

### ISSUE THREAD

**Issue by StaticLink** [ddinu/observable#35]
Hi Daniel,

Are the observable properties thread safe?

I see that observable_property<T> can be subscribed to with a std::function.
When this is run, does it spawn on a new thread, or does it run within the thread that modifies the observable_property<T>?

Best,
StaticLink

**Comment by StaticLink** [comment]
(Sorry about raising an issue which isn't as much an issue as it is a question 😃)

**Comment by ddinu** [comment]
No worries, I’m happy to answer any questions.

The library doesn’t spawn any threads on its own and everything runs on the
thread that modifies the property.

Regards,
Daniel

**Comment by StaticLink** [comment]
Many thanks - great, that makes it somewhat easier for us users to coordinate what runs where. My architecture is coming out nicely thanks to your library, but I'll be back with more questions sometime, no doubt. :-)Have a good one,/SLOn 19 Mar 2019 20:28, Daniel Dinu <notifications@github.com> wrote:No worries, I’m happy to answer any questions.



The library doesn’t spawn any threads on its own and everything runs on the

thread that modifies the property.



Regards,

Daniel



On Tue, Mar 19, 2019 at 12:15 PM StaticLink <notifications@github.com>

wrote:
