### ISSUE TITLE
Status of the observable project

### ISSUE THREAD

**Issue by tom-pratt** [ddinu/observable#36]
Hi, I really love this library. I see there has not been much activity lately. What is the status? Maybe it's working well for lots of people and no major development is required.

I made a small change in my fork to allow templated OBSERVABLE_ADAPT_FILTER which was very useful for my usecase of deserializing a stream of json strings of different types.

Are you still open to pull requests?

**Comment by ddinu** [comment]
Hi Tom, thanks for reaching out. I'm glad to hear you like the library, I hope it's been useful to you and others.

I haven't had much time for this library, but I'd be happy to check out your PR, a templated OBSERVABLE_ADAPT_FILTER sounds like an interesting and useful change.

-Daniel

**Comment by tom-pratt** [comment]
Great I created a PR
