### ISSUE TITLE
How do I get the widget from within the body of the first lambda in documentation?

### ISSUE THREAD

**Issue by Paultok** [ddinu/observable#4]
Can you explain me how would I get the reference to widget object from within the body of the first lambda in the example in the documentation? I am certainly missing something:

[](std::string const & new_value) { /* update the widget : HOW? */ }

**Comment by ddinu** [comment]
Hi @Paultok,

You're definitely not missing something. In the current example it's impossible to update the widget. I'll update the example.

The simplest solution would be to capture a reference to the widget from outside of the lambda:

```
WidgetModel widget_model;
Widget widget;

auto sub = widget_model.text.subscribe([&](std::string const & new_value) {
                                           widget.set_text(new_value);
                                       });
```

Does this help?

Regards,
Daniel

**Comment by Paultok** [comment]
Sure, makes sense. Thanks.

**Comment by ddinu** [comment]
Cool! Glad to help.
