### ISSUE TITLE
not thread safe

### ISSUE THREAD

**Issue by tnovotny** [ddinu/observable#5]
As far as I can tell, connecting / disconnecting from multiple threads is not safe.

**Comment by ddinu** [comment]
Hi @tnovotny,

Indeed, there was a bug with the way I was using shared_ptrs. It should be fixed now with the use of atomic_store_explicit and atomic_load_explicit. Was this your concern?

**Comment by tnovotny** [comment]
Maybe I'm just misread the code. I didn't see concurrent subscribes and unsubscribes working correctly. It seemed to me there should be either more locking or some lockfree datastructure to keep concurrent manipulations of the subscriptions defined and correct. I'll have a second look.

**Comment by ddinu** [comment]
I've added an explanation of how subscribing is supposed to work inside.

The short version is that subjects use a copy-on-write mechanism to reduce the need for locking the functions_ collection while a notification is running.

Hope it helps!

**Comment by ddinu** [comment]
I am going to close this issue, if you find any specific issue, please open a new issue and I will be happy to try and resolve it.
