### ISSUE TITLE
What workflow should we use?

### ISSUE THREAD

**Issue by DrOptix** [ddinu/observable#6]
There are a few workflows we can use. I know locally we can develop however we want, but I guess we can choose a standard workflow so everything will be clear for everybody.

Personally I like to use the [GitFlow workflow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/), but this means we need write access to `ddinu/observable`.

Another workflow is the so called [GitFlow for GitHub](https://datasift.github.io/gitflow/GitFlowForGitHub.html), based on pull requests.

Also we can define whatever workflow we want as long as we are consistent with the fact that this repository is the official one.

No matter what we choose I think at least a rule that states that we must mention the issue number in the feature branch's name is the minimum we should do.

**Comment by ddinu** [comment]
I think that the library is small enough that the simple GitHub workflow (with pull requests and feature branches) should work.

GitFlow is nice and all, but I'd like to make contributing as easy as possible. I don't want to impose any rules about how people should contribute, so a pull request is enough for me.

Once we start doing regular releases, we can formalize the rules a bit, but right now, the main rule is that master should work correctly at all times (not sure if I've followed this myself so far).

Mentioning the issue number in the commit is a good idea, at least for commits that are related to an issue.
